[repository]
name = "hyprscroller"
authors = ["dawser"]
commit_pins = [
    ["84ab8d11e8951a6551d1e1bf87796a8589da6d47", "7038ece24a53f98d6d4eef9759646261ee3fa07b"], # 0.35.0
    ["3875679755014997776e091ff8903acfb311dd2f", "01a2acd196158e72e35b1fa77ddd86bf21ca3674"], # 0.38.0
    ["360ede79d124ffdeebbe8401f1ac4bc0dbec2c91", "01a2acd196158e72e35b1fa77ddd86bf21ca3674"], # 0.38.1
    ["fe7b748eb668136dd0558b7c8279bfcd7ab4d759", "733cfebfd241ecb98298314986896ad46dad3ccd"], # 0.39.1
    ["cba1ade848feac44b2eda677503900639581c3f4", "1dc620667f5d0ae2aaac5d3340bd341fc73a683b"], # 0.40.0
    ["ea2501d4556f84d3de86a4ae2f4b22a474555b9f", "c9248b6495e898225a8816478d932a68b61e0a2c"], # 0.41.0
    ['9e781040d9067c2711ec2e9f5b47b76ef70762b3', '44c48d9d800d4aa679126677182354eff5c03c9c'], # 0.41.1
    ['918d8340afd652b011b937d29d5eea0be08467f5', '4121019cde46c80fce78cf985a4bb8a04f74712e'], # 0.41.2
    ['9a09eac79b85c846e3a865a9078a3f8ff65a9259', '3d8503afa712a4d4f4b48a79e6bd48847ecb912b'], # 0.42.0
    ['0f594732b063a90d44df8c5d402d658f27471dfe', '3cdf011b1641987448120f5c7f21acc9d7ed610c'], # 0.43.0
    ['0c7a7e2d569eeed9d6025f3eef4ea0690d90845d', '07dc4dcdb9123d3b9969331614ca934cb740229f'], # 0.44.0
    ['4520b30d498daca8079365bdb909a8dea38e8d55', 'fb555247e4b17f31740896d952cc7a9874c44be3'], # 0.44.1
    ['a425fbebe4cf4238e48a42f724ef2208959d66cf', '8d78856cddd1a16610c6e41243daf486e1087a07'], # 0.45.0
    ['500d2a3580388afc8b620b0a3624147faa34f98b', '8d78856cddd1a16610c6e41243daf486e1087a07'], # 0.45.1
    ['12f9a0d0b93f691d4d9923716557154d74777b0a', '8d78856cddd1a16610c6e41243daf486e1087a07'], # 0.45.2
    ['0bd541f2fd902dbfa04c3ea2ccf679395e316887', 'f477e656dd37c3fba77ca1d88e27575f26a9c2fa']  # 0.46.2
]

[hyprscroller]
description = "A plugin providing a scrolling layout, inspired by PaperWM"
authors = ["dawser"]
build = [
    "make release",
]
output = "hyprscroller.so"

